<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Rede
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Rede\Model\Source;

use Magento\Payment\Model\Source\Cctype as PaymentCctype;

class Cctype extends PaymentCctype
{
    protected $_brands = [
        'VI' => 'Visa',
        'MC' => 'Master',
        'AE' => 'Amex',
        'DI' => 'Discover',
        'JCB' => 'JCB',
        'DN' => 'Diners',
        'ELO' => 'Elo',
        'HIC' => 'Hipercard',
    ];

    /**
     * @return string[]
     */
    public function getAllowedTypes()
    {
        return array_keys($this->_brands);
    }

    /**
     * get card in format to send rede
     * @return array
     */
    public function getBrandFormatRede($brand)
    {
        if (isset($this->_brands[$brand])) {
            return $this->_brands[$brand];
        }

        return false;
    }
}