<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Rede
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Rede\Model\Source;

class CustomerAttribute
{
    /**
     * @var \Magento\Customer\Model\Customer
     */
    protected $_customer;

    public function __construct(\Magento\Customer\Model\Customer $customer)
    {
        $this->_customer = $customer;
    }

    public function toOptionArray()
    {
        $options = array();
        $attributes = $this->_customer->getAttributes();
        $options[] = ['label' => __('Select a Attribute'), 'value' => ''];
        foreach ($attributes as $attr) {
            $options[] = [
                'label' => $attr->getAttributeCode(),
                'value' => $attr->getAttributeCode(),
            ];
        }

        return $options;
    }
}