<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Model\Method\Dc\Transaction;

class Pending extends \Az2009\Cielo\Model\Method\Cc\Transaction\Pending
{
    public function process()
    {
        $payment = $this->getPayment();
        $bodyArray = $this->getBody(\Zend\Json\Json::TYPE_ARRAY);
        $paymentId = '';

        $payment->setAdditionalInformation(
            'transaction_authorization',
            $paymentId
        );

        if (isset($bodyArray['threeDSecure']['url'])
            && $url = $bodyArray['threeDSecure']['url']
        ) {
            $payment->setAdditionalInformation('redirect_url', $url);
        }

        $payment->setIsTransactionPending(true);

        return $this;
    }
}