<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Rede
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Rede\Model\Method\Cc\Transaction;

class Cancel extends \Az2009\Rede\Model\Method\Transaction
{
    public function __construct(
        \Magento\Customer\Model\Session $session,
        \Magento\Sales\Model\Order\Email\Sender\OrderCommentSender $comment,
        \Magento\Framework\Registry $registry,
        array $data = []
    ) {
        $this->_registry = $registry;
        parent::__construct($session, $comment, $data);
    }

    public function process()
    {
        $payment = $this->getPayment();
        $bodyArray = $this->getBody(\Zend\Json\Json::TYPE_ARRAY);
        $paymentId = '';
        $order = $payment->getOrder();

        if (!property_exists($this->getBody(), 'authorization') && !$payment->getLastTransId()) {
            throw new \Az2009\Rede\Exception\Cc(__('Payment not authorized'));
        } elseif(property_exists($this->getBody(), 'authorization')) {
            $paymentId = $this->getBody()->authorization->tid;
        }

        if (empty($paymentId) && !$payment->getLastTransId()) {
            throw new \Az2009\Rede\Exception\Cc(__('Payment not authorized'));
        }

        $isPaymentReview = $order->isPaymentReview();

        //check if is the first capture of order
        if (!$payment->getLastTransId() && !empty($paymentId)) {
            $payment->setTransactionId($paymentId)
                    ->setLastTransId($paymentId);
        } else {
            $payment->setParentTransactionId(
                $payment->getAdditionalInformation('transaction_authorization')
            );
        }

        $this->prepareBodyTransaction($bodyArray);

        $payment->setTransactionAdditionalInfo(
            \Magento\Sales\Model\Order\Payment\Transaction::RAW_DETAILS,
            $this->getTransactionData()
        );

        $payment->setIsTransactionClosed(true);
        if($isPaymentReview) {
            $order->registerCancellation();
        }

        if($order->canCreditmemo()) {
            $payment->registerRefundNotification($this->_getVoidedAmount());
        }

        $order->save();

        $this->addReturnMessageToTransaction($bodyArray);

        return $this;
    }

    protected function _getVoidedAmount()
    {
        return $this->getPayment()->getAmountOrdered();
    }
}