<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Rede
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Rede\Model\Method\Cc\Transaction;

class Unauthorized extends \Az2009\Rede\Model\Method\Transaction
{

    /**
     * @var \Psr\Log\LoggerInterface
     */
    protected $logger;


    public function __construct(
        \Psr\Log\LoggerInterface $logger,
        \Magento\Customer\Model\Session $session,
        \Magento\Sales\Model\Order\Email\Sender\OrderCommentSender $comment,
        array $data = []
    ) {
        $this->logger = $logger;
        parent::__construct($session, $comment, $data);
    }

    public function process()
    {
        $bodyArray = $this->getBody(\Zend\Json\Json::TYPE_ARRAY);

        $message = __('Unauthorized Payment Action');

        if (isset($bodyArray['authorization']['returnMessage'])) {
            $message = $bodyArray['authorization']['returnMessage'];
        }

        throw new \Az2009\Rede\Exception\Cc(
            __('The acquirer\'s response: %1', $message)
        );
    }

}