<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Rede
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Rede\Model\Method\Cc\Validate;

class Payment extends \Az2009\Rede\Model\Method\Validate
{
    protected $_fieldsValidate = [
        'Amount' => [
            'required' => true,
            'maxlength' => 10,
        ],
        'installments' => [
            'required' => true,
            'maxlength' => 2,
        ],
        'reference' => [
            'required' => true,
            'maxlength' => 16,
        ]
    ];

    public function validate()
    {
        $params = $this->getRequest();
        if (!isset($params)) {
            throw new \Az2009\Rede\Exception\Cc(__('Payment info invalid'));
        }

        $creditCard = $params;
        foreach ($creditCard as $k => $v) {
            $this->required($k,$v, __('Payment: '));
            $this->maxLength($k,$v, __('Payment: '));
        }
    }
}