<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Rede
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Rede\Model\Method\Dc\Validate;

class Customer extends \Az2009\Rede\Model\Method\Cc\Validate\Customer
{
    /**
     * @var array
     */
    protected $_fieldsValidate = [
        'Name' => [
            'required' => true,
            'maxlength' => 255,
        ]
    ];

    public function validate()
    {
        $params = $this->getRequest();
        if (!isset($params['Customer'])) {
            throw new \Az2009\Rede\Exception\Cc(__('Customer info invalid'));
        }

        $customer = $params['Customer'];
        foreach ($customer as $k => $v) {
            $this->required($k,$v, __('Customer: '));
            $this->maxLength($k,$v, __('Customer: '));
        }
    }
}