<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Rede
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Rede\Model\Method\Dc\Validate;

class DebitCard extends \Az2009\Rede\Model\Method\Cc\Validate\CreditCard
{

    /**
     * @var \Az2009\Rede\Helper\Dc
     */
    protected $helper;

    public function __construct(
        \Az2009\Rede\Helper\Dc $helper,
        array $data = []
    ) {
        parent::__construct($helper, $data);
        $this->helper = $helper;
    }

    /**
     * rules field
     * @var array
     */
    protected $_fieldsValidate = [
        'cardNumber' => [
            'required' => true,
            'maxlength' => 19,
        ],
        'cardHolderName' => [
            'required' => true,
            'maxlength' => 30,
        ],
        'expirationMonth' => [
            'required' => true,
            'maxlength' => 2,
        ],
        'expirationYear' => [
            'required' => true,
            'maxlength' => 4,
        ],
        'securityCode' => [
            'required' => true,
            'maxlength' => 4,
        ],
        'Brand' => [
            'required' => true,
            'maxlength' => 10,
        ]

    ];

    /**
     * Regex of credit card
     *
     * @var array
     */
    protected $_ccTypeRegExpList = [
        // Visa
        'Visa' => '/^4[0-9]{12}([0-9]{3})?$/',

        // Master Card
        'Master' => '/^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$/',
    ];

    /**
     * Validate fields
     *
     * @throws \Az2009\Rede\Exception\Cc
     */
    public function validate()
    {
        $params = $this->getRequest();
        if (!isset($params['cardNumber'])) {
            throw new \Az2009\Rede\Exception\Cc(__('Invalid Debit Card Info'));
        }

        $creditCard = $params;
        foreach ($creditCard as $k => $v) {
            $this->required($k,$v, __('Debit Card: '));
            $this->maxLength($k,$v, __('Debit Card: '));
        }

        $this->isValidCreditCard($creditCard);
        $this->isValidDueDate($creditCard);
    }

    /**
     * Validate credit card number
     *
     * @param array $creditCard
     *
     * @throws \Az2009\Rede\Exception\Cc
     */
    public function isValidCreditCard(Array $creditCard)
    {
        if (!preg_match(
                $this->_ccTypeRegExpList[$creditCard['Brand']], $creditCard['cardNumber']
            )
        ) {
            throw new \Az2009\Rede\Exception\Cc(__('Invalid Debit Card'));
        }
    }
}