<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Model\Method\Dc\Validate;

class Payment extends \Az2009\Cielo\Model\Method\Cc\Validate\Payment
{
    protected $_fieldsValidate = [
        'Amount' => [
            'required' => true,
            'maxlength' => 10,
        ],
        'reference' => [
            'required' => true,
            'maxlength' => 16,
        ],
        'threeDSecure ' => [
            'required' => true
        ],
        'urls' => [
            'required' => true
        ],
    ];
}